import Header from '@/components/header';
import { EthProvider } from '@/contexts/EthContext';
import { ThemeProvider } from '@/providers/theme-provider';
import ToastProvider from '@/providers/toast-provider';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <EthProvider>
            <section className="section">
              <Header />
              <div className="wrapper">{children}</div>
            </section>

            <ToastProvider />
          </EthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
