import Header from '@/components/header';
import ToastProvider from '@/providers/toast-provider';
import './globals.css';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <section className="section">
            <Header />
            <div className="wrapper">{children}</div>
          </section>

          <ToastProvider />
        </ThemeProvider>
      </body>
    </html>
  );
}
